### PR TITLE
Created `get_all_tags` function in tag_requests.py

### PR DESCRIPTION
**Pull request by jsa-codes**
1. Created get_all_tags function
2. Also created the following imports:

> - sqlite3 
> - json
> - from models import Tag

### CODE REVIEW

**Review by adamfeatherston — CHANGES_REQUESTED** [review]
'''
t.id
''' 
in SELECT statement

**Review by adamfeatherston — CHANGES_REQUESTED** [review]
return tags 

json.dumps will be done in requesthandler.py

**Comment by jsa-codes** [comment]
@adamfeatherston Fixed it.

**Comment by jsa-codes** [comment]
Fixed it to now return tags

**Review by adamfeatherston — APPROVED** [review]

**Pull request merged**
